FROM pytorch/pytorch
RUN pip install pytorch-lightning  
RUN pip install jupyterlab
RUN pip install pandas
RUN pip install numpy
RUN pip install scipy 
RUN pip install matplotlib 
RUN pip install ipython 
RUN pip install jupyter 
RUN pip install pandas 
RUN pip install sympy 
RUN pip install nose
RUN pip install einops

CMD jupyter-lab --ip 0.0.0.0 --port 8888 --no-browser --allow-root
#CMD sh
