version: "3.8"
services: 
  lab: 
    build: .
    ports: 
      - 8888:8888
    runtime: nvidia
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all 
    volumes: 
      - ./:/app
    working_dir: /app
    stdin_open: true 
    tty: true  
  
